// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" data-theme=\"light\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"/static/js/htmx.min.js\"></script><link href=\"/static/css/daisyui.css\" rel=\"stylesheet\" type=\"text/css\"><script src=\"/static/js/tailwindcss.js\"></script><script src=\"/static/js/hyperscript.js\"></script><style>\n\t\t\t\t:root {\n\t\t\t\t\t--bazzite-purple: #5e43f3;\n\t\t\t\t\t--bazzite-purple-dark: #4935c8;\n\t\t\t\t\t--bazzite-text: #333333;\n\t\t\t\t\t--bazzite-bg: #f5f5f7;\n\t\t\t\t}\n\t\t\t\tbody {\n\t\t\t\t\tfont-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;\n\t\t\t\t\tbackground-color: var(--bazzite-bg);\n\t\t\t\t\tcolor: var(--bazzite-text);\n\t\t\t\t\tpadding-top: 60px; /* Add padding to prevent content from hiding under the sticky header */\n\t\t\t\t}\n\t\t\t\t.btn-primary {\n\t\t\t\t\tbackground-color: var(--bazzite-purple) !important;\n\t\t\t\t\tborder-color: var(--bazzite-purple) !important;\n\t\t\t\t}\n\t\t\t\t.btn-primary:hover {\n\t\t\t\t\tbackground-color: var(--bazzite-purple-dark) !important;\n\t\t\t\t\tborder-color: var(--bazzite-purple-dark) !important;\n\t\t\t\t}\n\t\t\t\t.navbar {\n\t\t\t\t\tbackground-color: #222222;\n\t\t\t\t\tpadding: 0.5rem 1rem;\n\t\t\t\t}\n\t\t\t\t.navbar a {\n\t\t\t\t\tcolor: white;\n\t\t\t\t}\n\t\t\t\t.logo {\n\t\t\t\t\tdisplay: flex;\n\t\t\t\t\talign-items: center;\n\t\t\t\t}\n\t\t\t\t.logo img {\n\t\t\t\t\theight: 40px;\n\t\t\t\t\twidth: auto;\n\t\t\t\t}\n\t\t\t\t.sticky-header {\n\t\t\t\t\tposition: fixed;\n\t\t\t\t\ttop: 0;\n\t\t\t\t\tleft: 0;\n\t\t\t\t\tright: 0;\n\t\t\t\t\tz-index: 1000;\n\t\t\t\t\tbox-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n\t\t\t\t}\n\t\t\t</style><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/components/layout.templ`, Line: 58, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " | Bazzite Portal</title></head><body hx-boost=\"true\"><header class=\"sticky-header\"><nav class=\"navbar flex justify-between\"><div class=\"logo\"><a href=\"/\"><img src=\"/static/images/logo.png\" alt=\"Bazzite Logo\"></a></div><div><ul class=\"menu menu-horizontal\"><li><a href=\"/\">Home</a></li><li><a href=\"https://bazzite.gg\" target=\"_blank\">About</a></li><li><a href=\"https://docs.bazzite.gg\" target=\"_blank\">Docs</a></li></ul></div></nav></header><main class=\"container mx-auto max-w-4xl\"><div class=\"p-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></main><footer class=\"p-6 text-center text-gray-500 text-sm\"><p>Bazzite Portal • Powered by Yafti-Go</p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
